export enum VehicleBodyType {
  CONVERTIBLE = "CONVERTIBLE",
  COUPE = "COUPE",
  HATCHBACK = "HATCHBACK",
  LUXURY_SEDAN = "LUXURY_SEDAN",
  MPV = "MPV",
  SEDAN = "SEDAN",
  SPORTS = "SPORTS",
  STATION_WAGON = "STATION_WAGON",
  SUV = "SUV",
  TRUCK = "TRUCK",
  VAN = "VAN",
}
